from BinaryTree import BinaryTree, Node
import math

bt = BinaryTree(1)
bt.insert(5)
bt.insert(6)
bt.insert(10)
bt.insert(2)
bt.insert(13)
bt.insert(99)
bt.insert(21)
bt2 = BinaryTree(23)
bt2.insert(7)
bt2.insert(16)
bt2.insert(8)
bt2.insert(4)
bt2.insert(88)
bt2.insert(72)
#bt2.inorder()
bt.merge(bt2)
#print(bt.max())
#print(bt.min())
#bt.inorder()
#bt.preorder()
print("root" + str(bt.root.data))
print()
bt.preorder()
print()
bt.remove(1)
print()
print(bt.preorder())
print(bt.root.data)
#bt.inorder()

